<a href="https://colab.research.google.com/github/MANMOHAN04/Pandas/blob/main/DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

#Creating a DataFrame

In [ ]:
#lists
student_data =[
    [100,67,89],
    [99,78,90],
    [56,89,98],
    [98,45,77],
    [96,99,100]
]
pd.DataFrame(student_data,columns=['iq','marks','points'])

    iq  marks  points
0  100     67      89
1   99     78      90
2   56     89      98
3   98     45      77
4   96     99     100

In [ ]:
#dictionary
student_dict={
    'name':['x','y','z','a','b','c','d'],
    'iq':[100,89,97,94,93,0,0],
    'marks':[96,65,78,25,98,0,0],
    'point':[58,55,98,91,90,0,0]
}
students=pd.DataFrame(student_dict)
students.set_index('name',inplace=True)
students

       iq  marks  point
name
x     100     96     58
y      89     65     55
z      97     78     98
a      94     25     91
b      93     98     90
c       0      0      0
d       0      0      0

In [ ]:
students.duplicated().sum()

1

In [ ]:
movies=pd.read_csv('/content/movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [ ]:
ipl=pd.read_csv('/content/ipl-matches.csv')
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

#DataFrame Attributes and Methods

In [ ]:
#shape
movies.shape

(1629, 18)

In [ ]:
#dtypes
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [ ]:
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [ ]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [ ]:
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']], dtype=object)

In [ ]:
#sample
movies.sample(5)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1394,Koi... Mil Gaya,tt0254481,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Koi..._Mil_Gaya,Koi... Mil Gaya,Koi... Mil Gaya,0,2003,171,Action|Drama|Romance,7.1,19430,Scientist Sanjay Mehra devises a computer that...,A developmentally disabled young man tries to ...,You are not alone,Rekha|Hrithik Roshan|Preity Zinta|Rakesh Rosha...,27 wins & 30 nominations,8 August 2003 (USA)
851,Apartment (film),tt1425618,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Apartment_(film),Apartment: Rent at Your Own Risk,Apartment: Rent at Your Own Risk,0,2010,97,Drama|Mystery|Thriller,3.4,206,Employed as an Air Hostess with Spice Jet Mum...,A jilted woman feels threatened after renting ...,Who would you like as your roommate?,Rohit Roy|Tanushree Dutta|Neetu Chandra|Mushta...,NaN,23 April 2010 (India)
631,John Day (film),tt2699840,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/John_Day_(film),John Day,John Day,0,2013,138,Drama,5.7,735,John Day is a bank manager and lives with his ...,John Day is a bank manager and lives with his ...,NaN,Naseeruddin Shah|Randeep Hooda|Elena Kazan|She...,NaN,13 September 2013 (India)
349,Moh Maya Money,tt5343678,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Moh_Maya_Money,Moh Maya Money,Moh Maya Money,0,2016,108,Crime|Drama|Thriller,5.7,344,A young real-estate broker tries to pull off a...,A young real-estate broker tries to pull off a...,NaN,Neha Dhupia|Ranvir Shorey|Devendra Chowhan|Vid...,NaN,25 November 2016 (India)
585,Mere Dad Ki Maruti,tt2323964,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Dad_Ki_Maruti,Mere Dad Ki Maruti,Mere Dad Ki Maruti,0,2013,101,Comedy|Drama|Romance,6.4,4224,Twenty-something Sameer is a brat who thinks h...,In the midst of a loud Punjabi wedding a boy ...,NaN,Saqib Saleem|Rhea Chakraborty|Ram Kapoor|Praba...,4 nominations,15 March 2013 (India)

In [ ]:
#info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [ ]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [ ]:
#isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [ ]:
#duplicated
movies.duplicated().sum()

0

In [ ]:
#rename
students.rename(columns={'marks':'percent','point':'pt'},inplace=True)
students

       iq  percent  pt
name
x     100       96  58
y      89       65  55
z      97       78  98
a      94       25  91
b      93       98  90
c       0        0   0
d       0        0   0

#Math Methods

In [ ]:
#sum
movies.sum()

<ipython-input-19-ab2e624386de>:2: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  movies.sum()

title_x            Uri: The Surgical StrikeBattalion 609The Accid...
imdb_id            tt8291224tt9472208tt6986710tt8108208tt6028796t...
wiki_link          https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y            Uri: The Surgical StrikeBattalion 609The Accid...
original_title     Uri: The Surgical StrikeBattalion 609The Accid...
is_adult                                                           0
year_of_release                                              3274720
runtime            1381311121211029710910414812013415314313014311...
genres             Action|Drama|WarWarBiography|DramaCrime|DramaD...
imdb_rating                                                   9053.1
imdb_votes                                                   8770965
summary            Indian army special forces execute a covert op...
dtype: object

In [ ]:
students.sum()

iq         473
percent    362
pt         392
dtype: int64

In [ ]:
#mean
students.mean()

iq         67.571429
percent    51.714286
pt         56.000000
dtype: float64

In [ ]:
students.median()

iq         93.0
percent    65.0
pt         58.0
dtype: float64

#selecting cols from a Data Frame

In [ ]:
#singl column
movies['title_y']

0            Uri: The Surgical Strike
1                       Battalion 609
2       The Accidental Prime Minister
3                     Why Cheat India
4                     Evening Shadows
                    ...
1624            Tera Mera Saath Rahen
1625             Yeh Zindagi Ka Safar
1626                  Sabse Bada Sukh
1627                            Daaka
1628                         Humsafar
Name: title_y, Length: 1629, dtype: object

In [ ]:
#multiple columns
movies[['title_x','runtime','year_of_release']]

                                   title_x runtime  year_of_release
0                 Uri: The Surgical Strike     138             2019
1                            Battalion 609     131             2019
2     The Accidental Prime Minister (film)     112             2019
3                          Why Cheat India     121             2019
4                          Evening Shadows     102             2018
...                                    ...     ...              ...
1624                 Tera Mera Saath Rahen     148             2001
1625                  Yeh Zindagi Ka Safar     146             2001
1626                       Sabse Bada Sukh      \N             2018
1627                                 Daaka     136             2019
1628                              Humsafar      35             2011

[1629 rows x 3 columns]

#Selecting row from a DataFrame



*   iloc:- searches using index positions
*   loc:- searches using index labels

In [ ]:
#single row
movies.iloc[5]

title_x                                                   Soni (film)
imdb_id                                                     tt6078866
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link                   https://en.wikipedia.org/wiki/Soni_(film)
title_y                                                          Soni
original_title                                                   Soni
is_adult                                                            0
year_of_release                                                  2018
runtime                                                            97
genres                                                          Drama
imdb_rating                                                       7.2
imdb_votes                                                       1595
story               Soni  a young policewoman in Delhi  and her su...
summary             While fighting crimes against women in Delhi  ...
tagline                                                           NaN
actors              Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...
wins_nominations                               3 wins & 5 nominations
release_date                                    18 January 2019 (USA)
Name: 5, dtype: object

In [ ]:
#multiple row
movies.iloc[0:5]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [ ]:
#fancy indexing

movies.iloc[[0,5,8,10]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)

In [ ]:
#loc
students.loc['x']

iq         100
percent     96
pt          58
Name: x, dtype: int64

In [ ]:
students.loc['x'::2]

       iq  percent  pt
name
x     100       96  58
z      97       78  98
b      93       98  90
d       0        0   0

In [ ]:
movies.iloc[0:3,0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

#Filtering a DataFrame

In [ ]:
ipl.head(3)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [ ]:
#Find all the final winners
# new_df=ipl[ipl['MatchNumber']=='Final']
# new_df[['Season','WinningTeam']]

ipl[ipl['MatchNumber']=='Final'][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [ ]:
#how many super over finishes have occured

ipl[ipl['SuperOver']=='Y'].shape[0]

14

In [ ]:
#how many matches has csk won in Kolkata
ipl[(ipl['City']=='Kolkata')&(ipl['WinningTeam']=='Chennai Super Kings')].shape[0]

5

In [ ]:
#toss winner is the match winner in percentage

(ipl[ipl['TossWinner']==ipl['WinningTeam']].shape[0]/ipl.shape[0])*100

51.473684210526315

In [ ]:
#movies with rating greater than 8 and votes>10000
movies[(movies['imdb_rating']>8) & (movies['imdb_votes']>10000)].shape[0]

43

In [ ]:
#Action movies with rating higher than 7.5  ->.str.contains('Action)
movies[(movies['genres'].str.split('|').apply(lambda x:'Action' in x)) & (movies['imdb_rating']>7.5)].shape[0]

33

#Adding new cols

In [ ]:
#Completly new
movies['country']='IND'

In [ ]:

movies.dropna(inplace=True)

In [ ]:
#from existing one
movies['lead_actors']=movies['actors'].str.split('|').apply(lambda x:x[0])
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country,lead_actors
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),IND,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),IND,Gavie Chahal
37,Article 15 (film),tt10324144,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Article_15_(film),Article 15,Article 15,0,2019,130,Crime|Drama,8.3,13417,In the rural heartlands of India an upright p...,In the rural heartlands of India an upright p...,Farq Bahut Kar Liya| Ab Farq Laayenge.,Ayushmann Khurrana|Nassar|Manoj Pahwa|Kumud Mi...,1 win,28 June 2019 (USA),IND,Ayushmann Khurrana

#Import DataFrame Functions

In [ ]:
#astype
ipl['Season']= ipl['Season'].astype('category')
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(1), float64(1), int64(1), object(17)
memory usage: 142.7+ KB